# Generated by Django 3.2.16 on 2023-02-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coach_nail',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.DateTimeField()),
                ('path', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='coach_shoulder',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.DateTimeField()),
                ('path', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='coach_turtle',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.DateTimeField()),
                ('path', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20)),
            ],
        ),
    ]
